version: 1
release:
  # Branch configuration
  branch: main

  # Version bump type
  defaultBump: patch

  # Version file updates
  version:
    files:
      - path: 'package.json'
        pattern: "\"version\":\\s*\"(?<version>[^\"]+)\""
        template: '"version": "${version}"'

  # Changelog configuration
  changelog:
    enabled: true
    template: conventional

  # Pre-release checks
  checks:
    - type: install
      command: 'npm install'

    - type: build
      command: 'npm run build'

  # Release actions actions
  actions:
    - type: git-tag
    - type: commit-push
    - type: github-release
      assets:
        - 'dist/xtranslate.es.js'
        - 'dist/xtranslate.umd.js'
